- poetry.lock
- pyproject.toml
- Add boto3 and related type stubs for AWS SDK integration
- Include weni-agents-toolkit and requests libraries
- Update FastAPI version
- Modify project packaging configuration
- Add additional development dependencies for testing and type checking
> Chore: Update dependencies

- app/clients/nexus_client.py
- app/clients/tests/__init__.py
- app/clients/tests/test_nexus_client.py
- app/core/config.py
- Features
- Implement NexusClient for pushing agents
- Include environment-specific configuration for Nexus integration
- Tests
- Implement test suite for NexusClient
- Cover initialization, agent pushing, and error handling scenarios
- Add fixtures for test data and client instantiation
- Verify request details, headers, and multipart form data
> Feat: Nexus client

- .coveragerc
- poetry.lock
- pyproject.toml
- pytest.ini
- Upgrade dependencies to latest versions
- Remove unnecessary dependencies (black, weni-agents-toolkit)
- Update pytest, ruff, and other development tools
- Consolidate pytest configuration in pyproject.toml
- Remove separate pytest.ini file
> chore: Update project dependencies and configuration

- app/clients/tests/test_nexus_client.py
- app/services/__init__.py
- app/services/skill/__init__.py
- app/services/skill/tests/__init__.py
- app/services/skill/tests/test_validator.py
- app/services/skill/validator.py
- tests/__init__.py
- tests/api/__init__.py
- tests/api/v1/__init__.py
- tests/api/v1/routers/__init__.py
- Implement requirements file validation for skill packages
- Create validator with multiple safety checks:
* File existence and size validation
* Package count limitation
* Detection of dangerous and unsafe package patterns
- Add unit tests covering various validation scenarios
- Introduce modular validation functions with clear error reporting
> feat: Add skill package validation service

- app/services/skill/__init__.py
- app/services/skill/packager.py
- app/services/skill/templates/lambda_function.py.template
- app/services/skill/tests/test_packager.py
- Feature
- Implement skill packaging utility to create deployable Lambda function zips
- Add dependency installation with security validation
- Create dynamic Lambda function entry point generation
- Support extracting, processing, and re-zipping skill packages
- Include comprehensive logging and error handling
- Add Lambda function template for consistent skill execution
- Tests
- Implement detailed test coverage for skill packaging functions
- Add test cases for dependency installation, Lambda function generation
- Cover scenarios including successful packaging, error handling, and edge cases
- Test validation, zip creation, and temporary file management
- Ensure robust testing of packager utility functions
> feat: Add skill packaging service with Lambda function generation

- .env.example
- app/api/v1/routers/agents.py
- app/api/v1/routers/tests/test_agents.py
- app/api/v1/routes.py
- app/services/skill/packager.py
- poetry.lock
- pyproject.toml
- Feature
- Implement `api/v1/agents` endpoint for processing and uploading skill configurations
- Add support for streaming responses during agent processing
- Create utility functions for skill file extraction and processing
- Integrate with Nexus client for agent upload
- Add comprehensive logging and error handling
- Support dynamic skill packaging and entrypoint generation
- Include environment configuration for Nexus base URL
- Tests
- Add pytest-asyncio dependency to poetry.lock and pyproject.toml
- Configure pytest to use asyncio mode automatically
- Enable async testing capabilities for the project
- Implement detailed test coverage for agents configuration API
- Add test cases for successful agent processing, error scenarios, and edge cases
- Cover streaming response handling, …
> feat: Add agents configuration endpoint with Nexus integration

- app/core/config.py
- docker/docker-entrypoint.sh
- Add comprehensive logging for environment configuration
- Implement debug logging for environment variables
- Update log level to uppercase for consistency
- Add nested delimiter for environment variable parsing
- Improve settings initialization with diagnostic logging
- Ignore extra environment variables to prevent configuration errors
> refactor: Enhance configuration logging and environment variable handling

- app/api/v1/models/__init__.py
- app/api/v1/models/requests.py
- Create base request model with project UUID, definition, and toolkit version
- Implement RunSkillRequestModel for skill execution requests
- Add type hints and Pydantic validation for request models
> feat: Add API request models

- app/clients/aws/__init__.py
- app/clients/aws/lambda_client.py
- app/clients/aws/tests/test_lambda_client.py
- app/core/config.py
- Create AWSLambdaClient with methods for creating, deleting, and invoking Lambda functions
- Implement function creation with configurable parameters and logging
- Add async method to wait for Lambda function activation
- Update core configuration to include AWS-related settings
- Configure logging to suppress python_multipart warnings
> feat: Add AWS Lambda client implementation

- app/clients/aws/__init__.py
- app/clients/aws/logs_client.py
- app/clients/aws/tests/test_logs_client.py
- Implement AWSLogsClient to retrieve Lambda function logs
- Add support for fetching logs with configurable time range
- Include retry mechanism for log group retrieval
- Update AWS clients package to export new logs client
- Implement error handling and logging for log retrieval
> feat: Add AWS CloudWatch Logs client for Lambda function logs

- app/api/v1/routers/agents.py
- app/api/v1/routers/tests/test_agents.py
- app/services/skill/templates/lambda_function.py.template
- Introduce BaseRequestModel to consolidate form data parameters
- Update configure_agents endpoint to use unified request model
- Reduce parameter complexity and improve type safety
- Remove direct form parameter annotations in favor of structured model
- Update logging and processing logic to use new request model
> refactor: Simplify agent configuration request handling

- app/clients/tests/__init__.py
- app/clients/tests/test_weni_client.py
- app/clients/weni_client.py
- app/core/config.py
- Implement WeniClient to interact with Weni API for project authorization
- Add comprehensive test suite for WeniClient with various scenarios
- Update core configuration to include Weni API URL
- Enhance error handling and test coverage for authorization checks
> feat: Add WeniClient for project authorization checks

- app/api/v1/routers/runs.py
- app/api/v1/routers/tests/test_agents.py
- app/api/v1/routers/tests/test_runs.py
- app/clients/aws/lambda_client.py
- app/clients/aws/logs_client.py
- app/clients/aws/tests/test_lambda_client.py
- app/clients/aws/tests/test_logs_client.py
- app/core/config.py
- Add request ID tracking for Lambda function invocations
- Update logs client to filter logs by specific request ID
- Modify function name generation to use consistent CLI prefix
- Add log group configuration to Lambda function creation
> feat: Improve Lambda function logging and request tracking

- app/api/v1/routers/runs.py
- app/clients/aws/lambda_client.py
- app/clients/aws/logs_client.py
- app/clients/aws/tests/test_lambda_client.py
- app/clients/aws/tests/test_logs_client.py
- Update Lambda client to use datetime for precise timestamp tracking
- Add end_time parameter to logs client for more accurate log filtering
- Extend log retrieval time range by 1 minute before and after function execution
- Modify runs router to pass end_time for comprehensive log capture
> feat: Improve Lambda function timing and log retrieval

- app/core/config.py
- app/main.py
- poetry.lock
- pyproject.toml
This commit adds the Sentry SDK to the FastAPI application for enhanced error tracking and performance monitoring. The Sentry DSN is configured in the settings, and integrations for FastAPI and Starlette are established to capture transaction data and failed request status codes. Additionally, the poetry.lock and pyproject.toml files are updated to include the Sentry SDK dependency.
> feat: Integrate Sentry SDK for error tracking and performance monitoring

- README.md
This PR enhances the README.md by adding detailed sections on project features, prerequisites, setup instructions, testing, and Docker usage for both development and production environments. It also includes CI/CD badges for better visibility of the project's build status.
> docs: Update README.md with project features, setup instructions, and Docker usage

- CHANGELOG.md
This commit documents the addition of the permissions router and verify permission endpoint, integration of the Sentry SDK for error tracking and performance monitoring, and updates to the README.md with project features, setup instructions, and Docker usage.
> docs: Update CHANGELOG.md for version 1.1.0

- app/core/config.py
- app/services/skill/packager.py
- app/services/skill/templates/lambda_function.py.template
- app/services/skill/tests/test_packager.py
This commit introduces a new `Package` dataclass for managing package installations and refactors the `install_toolkit` function into `install_packages` to support multiple packages. The Sentry DSN is now dynamically included in the Lambda function template, improving error tracking capabilities. Additionally, tests are updated to reflect these changes.
> Enhance package installation and Sentry integration

- CHANGELOG.md
Adding entries for VersionCheckMiddleware and enhancements to package installation and Sentry integration.
> docs: Update CHANGELOG.md for version 1.2.0

- app/api/v1/routers/tool_logs.py
- Added logging for exceptions when retrieving log group ARN, improving traceability of errors.
- Updated exception handling to catch general exceptions instead of just KeyError.
> feat: Enhance error handling in get_logs endpoint

- CHANGELOG.md
- Added enhancement for error handling in get_logs endpoint.
> chore: Update CHANGELOG for version 1.5.1

- app/services/package/__init__.py
- app/services/package/package.py
- app/services/tool/packager.py
- app/services/tool/tests/templates/test_lambda_function.py.template
- app/services/tool/tests/test_packager.py
This PR introduces the Packager class to handle package installation and dependency management. The new service include methods for installing packages from a list and from a requirements.txt file, along with a utility for building Lambda function files from templates. Additionally, the existing packager utility has been refactored to utilize these new classes, enhancing modularity and maintainability. Corresponding tests have been updated to reflect these changes.
> Refactor package installation services

- app/services/agents/passive/configurator.py
- app/services/agents/passive/tests/test_passive_configurator.py
This PR adds the PassiveAgentConfigurator class, which extends the AgentConfigurator to manage the configuration of passive agents. It includes methods for processing agent resources, handling tool processing, and pushing the configured agents to Nexus. The implementation features streaming responses for real-time updates during processing, along with comprehensive error handling. Additionally, tests are included to validate the functionality and robustness of the agent configuration process.
> feat: Introduce PassiveAgentConfigurator for agent configuration and processing
